#!/usr/bin/python3.9
# -*- coding: utf-8 -*-
# -*- python -*- 
# Part of syuppo package
# Copyright © 2019-2021 Venturi Jérôme : jerome dot Venturi at gmail dot com
# Distributed under the terms of the GNU General Public License v3

import sys

try:
    from syuppo.client import main
except ImportError:
    import os.path
    sys.path.insert(0, os.path.dirname(__file__))
    # Ensure a clean reload from the new location.
    if 'syuppo' in sys.modules:
        try: # py3 compat
            from importlib import reload
        except ImportError:
            pass
        
        reload(sys.modules['syuppo'])
        del sys.modules['syuppo']
    from syuppo.client import main

if __name__ == '__main__':
    sys.exit(main())
